### ISSUE TITLE
Error npm start

### ISSUE THREAD

**Issue by BWakonig** [webdesignio/webdesignio-cli#6]
```
eduroamstud-130-82-254-191:designio benediktwakonig$ webdesignio init 

    web-design.io • commander
      - ready to take off -

    I need your credentials on https://webdesignio.com
    to log you in or register a brand-new account.

E-Mail: benedikt.wakonig@gmail.com
Password: ********

Attempting registration ... exists
Fetching token ... done

    ✓ Successfully initialized test
      Use `npm start` to get up and running

eduroamstud-130-82-254-191:designio benediktwakonig$ npm start

> test@1.0.0 start /Users/benediktwakonig/designio
> node scripts/start

module.js:457
    throw err;
    ^

Error: Cannot find module '/Users/benediktwakonig/designio/scripts/start'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 start: `node scripts/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.0 start script 'node scripts/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benediktwakonig/designio/npm-debug.log
```

**Comment by domachine** [comment]
See my comment [here](https://github.com/webdesignio/webdesignio-cli/issues/5)

**Comment by BWakonig** [comment]
saw it, thank for the quick response! i am on it, cheers

**Comment by domachine** [comment]
Can I close this?
